let demoDescr = [];
// Presentation text of each demo. Note : the demo name is always printed first
// In comment : demo internal number, followed by the inscription above the door
demoDescr = {
  // Main menu screen
  'menuScreen': "|NOW LOADING|THE MAIN MENU||CODING BY MANIKIN|ALL GRAPHIX AND|THE MEGADETH FONT|BY SPAZ||MUSIC BY MAD MAX||USE ARROW KEYS AND|SPACE TO ENTER DEMOS",
  // 01 - 3D BALLS 3294
  'RedSector': "THE RED SECTOR|DEMO||CONVERTED TO ST|BY MANIKIN|ALL GRAPHICS BY|SPAZ||MUSIC BY MAD MAX||NOT QUITE SUCH AN|ORIGINAL AS I HOPED|BUT THAT'S MY TOUGH|SHIT FOR BEING SLOW!",
  // 02 - LAND SCROLL (this demo uses LEFT & RIGHT arrow keys) 1934
  'LandScroll': "THE LANDSCAPE|SCREEN||ALL CODING BY|MANIKIN (SURPRISE)||GRAPHICS BY SPAZ||CONTROL THE LAND|SCROLL USING THE ARROW KEYS||MUSIC BY MAD MAX",
  // 03 - DI MIND BOMB 1454
  'DiMindBomb': "THE DIGITAL|INSANITY GUEST|SCREEN NUMBER 1||THIS WICKED LITTLE|SCREEN IS BY ONE|OF OUR DUTCH|FRIENDS||ALLCODING: DIGITAL|          INSANITY||MUSIC BY WHITTAKER",
  // 04 - MOVING BACK 2584
  'MovingBack': "THE MOVING|BACKGROUND SCREEN||ALL CODING BY|(GUESS WHO!!!!!!)||ALL GRAPHIX BY HIS|BROTHER!||MUSIC BY XAM DAM||ORIGINAL FONT FROM|SOME RECORD COVER.|THIS ONE BY SPAZ",
  // 05 - PARA SCROLL 3303
  'ParaScroll': "THE 2 LAYER|MOVING BACKGROUND|SCREEN||ALL DESIGN,  CODING|AND WAVEFORMS|BY MANIKIN|GRAPHICS BY SPAZ|(WHAT A SMART ASS)||MUSIC BY MAD MAX|ONE OF THE BEST|BITS WE'VE RIPPED",
  // 06 - MEGA BALLS 1162
  'MegaBalls': "THE 3D MEGABALLS|SCREEN|OR WHAT HAPPENS TO|YOUR BALLS WHEN|YOU MATURE!!||WAVES AND CODING|BY MANIKIN|GRAPHICS BY SPAZ||MUSIC BY CHRISPY|NOODLE OF THE BBC|(IT'S BLOODY ACE!)",
  // 07 - PODO 611
  'PoDo': "THE P.D LIBRARY|INFO SCREEN||CODING:    MANIKIN|GRAPHICS:     SPAZ||BORDER CODE FROM|THE EXCEPTIONS|(IN A ROUND ABOUT|SORT OF WAY!!!!)||MUSIC AGAIN FROM|SOME OLD DEMO",
  // 08 - DI MATRIX 617
  'DiMatrix': "THE 2ND DIGITAL|INSANITY GUEST|SCREEN|THE MATRIX SCREEN||STEFAN DOES IT|AGAIN.||PLAY AROUND WITH|THIS FOR A WHILE|AND YOU WILL|PROBABLY GO MAD!!!||MUSIC BY UMM AHH?",
  // 09 - SPIRAL SCROLL 1341
  'SpiralScroll': "THE CYCLIC SCROLL||ALL CODING AND|FONTS AND STUFF BY|MANIKIN||BOUNCY FONT BY|SPAZ||MUSIC BY MAD MAX|FROM THE GAME|5TH GEAR",
  // 10 - BIG SPRITE 1901
  'BigSprite': "|THE BIG SPRITE|SCREEN|||CODING:    MANIKIN|GRAPHIX:      SPAZ|MUSIX:     MAD MAX||BORING AS HELL BUT|WE PUT IT IN FOR|THE LOVE OF THE FONT",
  // 11 - FOXX TUNNEL 2549
  'FoxTunnel': "THE FOXX GUEST|SCREEN|THE STAR-TUNNEL||THIS SCREEN IS BY|A GERMAN CREW|CALLED FOXX||CODING BY CHUCK|MUSIC BY TANGENS||ONCE LOADED PLEASE|WAIT FOR ABOUT|15 SECONDS",
  // 12 - SINUS 2364
  'Sinus': "THE DOTTIE|BIG SCROLL SCREEN||CODING, WORKFORMS,|AND BIG FONT|BY MANIKIN|OTHER GRAPHICS BY|SPAZ|MUSIC BY MAD MAX|||ONCE LOADED PLEASE|WAIT FOR ABOUT|15 SECONDS",
  // 13 - SYNTH 789
  'Synth': "THE DIGI-SYNTH|DEMO SCREEN||FEATURING THE WELL|WICKED NEW TLB|4 TRACK|ALL MUSIC AND|GRAPHICS BY SPAZ||CODING BY MANIKIN||BASED UPON AN|ORIGINAL ROUTINE|BY ROB POVLEY.",
  // 14 - SCROLL MASSACR! 358
  'ScrollMassacre': "THE SCROLLINE|MASSACRE||AN IDEA SPARKED|BY STEFAN POSTHUMA||MOST FONT BY SPAZ||CODING BY MANIKIN|INSPIRED BY THE FLAT||BET YOU NEVER SAW|THIS MANY SCROLLS|ON ONE SCREEN.",
  // 15 - B.B.C 355
  'BBC': "THE  BAD BREW CREW|'MINDBOMB'  SCREEN||CODED BY      ANDY|     (THE MAX)||SCROLLER BY  PILOT|             (THE)||SORYRY BUT NO RESET|WHILE ITS RUNNING!|AND IT DOESN'T WORK CORRECTLY ON STE'S",
  // 16 - VECTORS (Hidden screen. When in the ladder at the left of the door, go to right before reaching the upper platform) 1412
  'Vector': "THE VECTORS SCREEN||THIS IS THE HIDDEN|(BADLY!) SCREEN OF|OUR MIND-BOMB DEMO||ALL CODING 'N FONT|BY MANIKIN||MUSIC BY      WELL|I'LL GIVE YOU ONE|GUESS!",
  // 17 DI NO SHIT 614
  'NoShit': "NO SHIT!||THE 4TH DIGITAL|INSANITY SCREEN||ALL CODING BY|STEF (THE POST)|||MUSIC BY|THE MAD SLEEPY ONE|FROM TERAMIS BY|THALION SOFTWARE",
  // 18 - DI AH YEAH 3330
  'DiAhYeah': "AH YEAH!||THE 3RD DIGITAL|INSANITY SCREEN||ALL CODING BY|THE OUTCH IDIOT!||MUSIC BY|THE GERMAN IDIOT||FROM TERAMIS BY|THALION  SOFTWARE"
  // PS : Don't forget the reset screen !
};

// Allows to have the demo Javascript file from the number (eg DemosByNumber[13] = 'Synth')
let DemosByNumber = Object.keys(demoDescr);
let DemosTitle = DemosByNumber.map(k => demoDescr[k].split('||').shift().replaceAll('|',' ').trim());
DemosByNumber.forEach(k=>demoDescr[k] = demoDescr[k].split('|'));
