class MegaBalls {
  constructor(demoManager) {
    this.demoManager = demoManager;
    // Bind to this all internally called functions
    this.onKeyPressed = this.onKeyPressed.bind(this);
    this.main = this.main.bind(this);
    this.stop = this.stop.bind(this);
    this.end = this.end.bind(this);
  }

  // Loads resources and returns a Promise
  // You can make long precalculations here.
  load() {
    return Promise.all(this.demoManager.loadResource(['Hellfire_64x64_46.png'])).then(data => {
      [this.font] = data;
    });
  }

  // Initialize the demo (all resources are already loaded)
  // Initialize scrolltexts here (for example)
  init() {
    this.font.initTile(64,64,46);
    this.scrolltext = new scrolltext_horizontal();
    this.scrolltext.scrtxt = "OH GOD ANOTHER SCREEN AND ANOTHER FLAMING SCROLLINE.  SO WHAT DO YOU THINK OF MY THREE DIMENSIONAL SPRITES THEN?? I ACTUALLY FIRST WROTE SOME THREE D SPRITE ROUTINES IN APRIL LAST YEAR. THAT WAS  JUST AFTER DEF DEMO WAS RELEASED. I THOUGHT UP THE ALGORITHM ON THE BUS HOME FROM COLLEGE AFTER HAVING A LESSON ON DOUBLE ANGLE IDENTITIES.  THAT IS THE FIRST TIME I EVER LEARNED ANYTHING INTERESTING IN MATHS... ANYWAY NOW SIX MONTHS AND MANY REWRITES LATER THEY HAVE METAMORPHOSED INTO THESE ROUTINES. THE NICE SMOOTH COLOR CHANGE IDEA COMES FROM A GAME CALLED DUGGER. IT SEEMS TO WORK REALLY WELL ON MY MONITOR...  THIS SCREEN CHEATS  IN SOME WAYS IN ORDER TO OBTAIN ITS SPEED. THE WAVES ARE ALL WORKED BEFORE THEY ARE PLOTTED. THE GAP BETWEEN THE END OF ONE WAVE AND THE NEXT IS THE TIME TAKEN TO RECALCULATE THE POINTS. THE ROUTINE IS QUITE COMPLICATED NOW AND ALLOWS A LARGE AMOUNT OF CONTROL OVER THE SPRITES. THE EIGHT SPRITES CAN BE ARRANGED IN ANY FORM. THEY CAN THEN BE BOUNCED OR SPUN OR WOBBLED AND FADED IN AND OUT .   THE POSITIONS OF THE SHADOWS ARE WORKED OUT PREVIOUSLY AS WELL BUT THE SHADOWS THEMSELVES  ARE ACTUALLY NOTTED SPRITE MASKS.. IF YOU PROGRAM YOU WILL KNOW WHAT I MEAN.  ALL THE CODING AND THE GRAPHIX FOR THE SPRITE IN THIS SCREEN WAS DONE BY MANIKIN  IN ABOUT ONE WEEK DURING OCTOBER. AND THEN IN TYPICAL LOST BOYS FASHION IN MARCH NINETEEN NINETY I DECIDED AT ALMOST THE LAST MINUTE TO RE WRITE THE SCREEN WITH A FASTER SPRITE ROUTINE AND STARS.  ENCOURAGEMENT AND MORAL SUPPORT FROM IAN.. IE..  THATS FUCKING GOOD THAT IS TIM ...  THE FONT WAS DRAWN BY SPAZ AND THE SUPERB MUSIC IS BY CHRISPY NOODLE OF OUR GOOD FRIENDS BBC....  ADDITIONAL INFORMATION WAS OBTAINED FROM  THREE D GRAPHICS PROGRAMMING BY ABACUS  THIS IS NOW MY SIXTH SCREEN TOWARDS MIND BOMB AND I REALLY DO NOT KNOW WHAT I AM GOING TO DO NEXT STILL YOU WILL PROBABLY KNOW BY NOW SO I HOPE YOU LIKE IT...    MANY THANKS TO THE ENORMOUS AMOUNT OF PEOPLE WE SAW AT THE PC SHOW IN SEPTEMBER.  IT REALLY MADE US FEEL GOOD.  IF YOU HAPPENED TO BE AROUND OUR STAND YOU WOULD HAVE SEEN JUST ABOUT EVERY SINGLE GREAT PROGRAMMER ON THE ST.  WE EVEN HAD A VISIT FROM ES OF TEX ON THE WEDNESDAY. PLUS RICHARD KARSMAKERS AND STEFAN POSTHUMA OF ST NEWS. JOHN PHILLIPS AUTHOR OF NEBULUS. MEMBERS OF THE BULLFROG TEAM. ROB POVEY WHO WROTE QUARTET FOR MICRODEAL AND ALL SORTS OF OTHER PEOPLE. WE HAD AN ABSOLUTELY FABULOUS WEEK AND ALL OF US HAD JOB OFFERS FROM VARIOUS PEOPLE. SPAZ AND SAMMY JOE NOW WORK AS TRANSLATORS FOR GFA SYSTEM TECHNIK. SPAZ HAS A GRAPHICS ARTIST JOB. WE WERE ALSO OFFERED JOBS BY AMONGST OTHER HEWSON AND BEST OF ALL  FROM THE MEGA MIGHTY THALION SOFTWARE HOME OF THE DEMO WORLDS FINEST PROGRAMMERS. TEX. TNT CREW. LEVEL SIXTEEN. THE CAREBEARS ETC  THIS WAS JUST TO GOOD TO SAY NO TO SO I AM PROBABLY GOING TO WORK THERE NEXT SUMMER IN GUETERSLOH. JUST WAIT UNTIL YOU SEE SOME  OF THALIONS GAMES. THEY ARE ABSOLUTELY FANTASTIC. THEY WILL BE THE BEST GAMES PRODUCERS ON THE ST INSIDE A YEAR. THAT I TRULY BELIEVE . WELL I THINK THAT IS QUITE ENOUGH FOR ONE SCROLLINE. SO LETS WWWWWWWRRRRRRRAAAAAAAPPPPPPP....................                  ";
    this.running = true;
  }

  // Starts the demo and returns a Promise that will be resolved at the end
  // of the demo.
  start() {
    return new Promise(endCallback => {
      this.endCallback = endCallback;
      this.can = new canvas(640, 400, "main");
      this.ctx = this.can.contex;
      this.scrolltext.init(this.can, this.font, 12);
      document.body.addEventListener('keydown', this.onKeyPressed);
      window.requestAnimFrame(this.main);
    });
  }

  // Main loop, called by Codef requestAnimFrame
  main() {
    if (this.running) {
      this.can.clear();
      this.scrolltext.draw(0);
      window.requestAnimFrame(this.main);
    } else {
      this.end();
    }
  }

  stop() {
    this.running = false;
  }

  // removes event listeners before notifying the menu screen that the demo is finished
  end() {
    document.body.removeEventListener('keydown', this.onKeyPressed);
    this.endCallback();
  }

  // Event processor
  onKeyPressed(event) {
    if (event.key === ' ') {
      event.preventDefault();
      this.stop();
    }
  }
}