class MovingBack {
  constructor(demoManager) {
    this.demoManager = demoManager;
    // Bind to this all internally called functions
    this.onKeyPressed = this.onKeyPressed.bind(this);
    this.main = this.main.bind(this);
    this.stop = this.stop.bind(this);
    this.end = this.end.bind(this);
  }

  // Loads resources and returns a Promise
  // You can make long precalculations here.
  load() {
    return Promise.all(this.demoManager.loadResource([
            'mbg_font.png', 'bk-drop.png', 'bk-sprite.png', 'bk-bg.png', 'Shades Giana Sisters Remix.sndh'
        ])).then(data => [this.font, this.bckgnd, this.tlb_sprite, this.bckdrop, this.zik] = data);
  }

  // Initialize the demo (all resources are already loaded)
  // Initialize scrolltexts here (for example)
  init() {
    this.running = true;
    this.partY=0;
    this.loop=0;
    this.bob=0;
    this.bobinc=0.0005;
    this.bob1=0;
	this.scrollcanvas=new canvas(640,70);
	this.backgroundcanvas=new canvas(640,384);
	this.bgcanvas=new canvas(1280*2,768*2);

	this.bgcanvas.setmidhandle();

	for (var f1=0;f1<40;f1++){
		for (var f2=0;f2<24;f2++){
			this.bckgnd.draw(this.bgcanvas,f1*256,f2*64);
		}
	}

	this.font.initTile(66,66,32);

	this.scrolltext = new scrolltext_horizontal();
	this.scrolltext.scrtxt="                   WELCOME TO THE MOVING BACKGROUND SCREEN BY THE MEGA COOL LOST BOYS, AS WE JUST RAN OUT OF MEMORY ON THE MAIN MENU WE DECIDED TO CONTINUE HERE................ IN THIS SCROLLER WE ARE GOING TO DEAL WITH MORE GREETINGS, A LOT OF DRIVEL, FUNNY STORIES WHICH HAPPENED TO US DURING OUR CAREER, OTHER DEMOS, MUSIC AND MANY MORE THINGS,   WE MIGHT EVEN TELL YOU ABOUT OUR LOVE LIFE !!   WE DECIDED TO START WITH OUR LOVE LIFE BECAUSE SOME FUNNY THINGS HAPPENED TO  US RECENTLY, THE FIRST PERSON'S LOVE LIFE WE ARE GOING TO TALK ABOUT IS SPAZ'S. IT ALL STARTED WITH THE NIGHT BEFORE HIS 16TH BIRTHDAY, THE 17/18 OF FEBRUARY (ANY BIRTDAY CARDS CAN BE SENT TO TLB HQ). THE NIGHT BEFORE HIS BIRTHDAY. ALL THE HORNY WOMEN FROM HIS CLASS DECIDED TO GIVE A BIRTHDAY PARTY FOR HIM. AT THIS PARTY THEY INTENDED TO GET HIM VERY DRUNK (THEY SUCCEEDED), UNFORTUNATELY SPAZ DOES NOT REMEMBER MUCH OF THIS PARTY. AT 10.30 PM THE PARENTS CHUCKED  EVERYBODY OUT, BUT AS SPAZ WAS PISSED OUT OF HIS BRAINS, HE HAD TO BE CARRIED TO THE BUS STOP. WHEN HE WOKE UP THE NEXT MORNING IN HIS BED, HE HAD ALL THESE PHONENUMBERS WRITTEN OVER HIS BODY (IN SOME WEIRD PLACES...). ANYWAY, LAST  NIGHT WE PHONED UP SOME ONE OF THESE NUMBERS AND GOT INVITED OUT, SO WE MET THEM ALL AND WENT TO THE OFF LICENCE AND BOUGHT: THUNDERBIRD, VODKA, LODSA BEER, WHISKY, DR. PEPPER, COKE, MARTINI AND WINE. ALLTOGETHER WE WERE 5 GUYS AND 3  GIRLS, THE GIRLS LOOKED BLOODY NICE, SPAZ LIKED ONE OF THEM ESPECIALLY, HELEN. WHEREAS SAMMY JOE PREFERRED SAFFREN (WEIRD NAME EHHH?). WHEN WE WERE TOTALLY PISSED OUT OF OUR BRAINS AT 9 PM AT SOME KIDDIES PLAYGROUND SPAZ TURNED TO HELEN AND SAID, 'WILL YOU GO OUT WITH ME ?' SHE REPLYED 'YOUR DRUNK', SOMEBODY ELSE SAID, 'SHE DOES NOT WANT TO GO OUT WITH YOU BECAUSE YOU HAVE LONG HAIR', SPAZ TOTALLY DISSAPOINTED FELL OVER AND CHUCKED UP ON THE PAVEMENT. GOD THAT  WAS A MESS. BUT A BIT LATER HELEN TOLD SPAZ THAT SHE WILL GIVE HIM A DEFINITE ANSWER TOMORROW IN SCHOOL. LATER THAT EVENING, WHEN WE LEFT THE PLAYGROUND, SOME 5 GUYS WITH KNIVES STARTED CHASING US. WE ALL STARTED RUNNING, BUT AS SPAZ WAS TOO PISSED, HE FELL INTO SOME DRIVE WAY. I (SAMMY JOE)  JUST ABOUT MANAGED TO RUN ON. WHEN WE LATER LOOKED FOR SPAZ, WE COULD NOT FIND HIM ANYWERE. SO THE REST OF US WENT BACK TO MY PLACE (AT 11 PM) AND WE WATCHED COCKTAIL. I  STARTED TO PLAY AROUND WITH SAFFREN BUT SHE TOLD ME TO GET LOST AND HER BOYFRIEND CAME UP AND I RETREATED. THE NEXT MORNING MY ROOM LOOKED A BLOODY MESS AND I HAD A BAD HANGOVER!!! IF YOU WANT TO FIND OUT ABOUT HELEN'S ANSWER, READ ON, WE WILL TELL YOU TOMORROW EVENING WHEN WE FINSIH OFF THE SCROLLINE.   IF THERE ARE ANY NICE GIRLS OUT THERE OR YOU HAVE A NICE PICTURE, WRITE TO US WITH A PICTURE AND WE WILL PROMISE TO ANSWER YOUR LETTER!!! ME(SAMMY JOE) AND SPAZ ARE WELL HANDSOME. HERE IS OUR ADDRESS: SPAZ AND SAMMY JOE, 22 OXFORD ROAD, TEDDINGTON, MIDDLESEX, TW11 OPZ.   NOW WE ARE GOING TO HAVE SOME MORE GREETINGS, HEREWITH WE SAY HI TO THE FOLLOWING PEOPLE:   ALCOHOLICA (GREAT SAMPLE DEMOS, WHEN IS NO MORE MR NICE GUY GOING TO BE RELEASED??), TCB, TBC, THE BATS CREW, THE UNION AND ALL THERE MEMBERS, PINK SHIRT GUY, THE SMURFS, THE FRAGGELS (GREAT MUSIX), HELEN (LODSA KISSES, SPAZ), KAREN (YOU LOOK PRETTY DAMN GOOD), HITLER (LOVE YOUR WORLD TOUR FROM 1939-45), NEW LINE, STAN THE MAN, THE ALLIANCE, HARVEY LODDER (ZIPPY),  GOOD GREEETINGS ARE SO BORING, IF YOU HAVE NOT BEEN GREETED WE MIGHT GREET YOU LATER..... NOW LETS SWAP THE SUBJECT AND TALK ABOUT OUR GREAT MUSIX TASTE, HERE ARE THE BANDS WE (YES IT IS STILL ME (SAMMY JOE) AND SPAZ WHO ARE TYPING) LIKE: METALLICA, FAITH NO MORE, SPERMBIRDS (GREAT LYRICS, IF YOU WANT TO KNOW WHAT THE LYRICS ARE,  READ THEM IN THE LOST BOYS PD LIBRARY SCROLLER), MEGADETH, METAL CHURCH (THAT IS GREAT MUSIX THAT STEFAN (POSTERIA) AND RICHARD CARCRASHERS), WARLOCK, AC/DC, RED HOT CHILLY PEPPERS, ALICE COOPER, ONSLAUGHT, SLAYER (THE BEST), THE ALLMIGHTY, JEZEBELL, GANG GREEN, SLAMMER, TREASON, HELLOWEEN, PINK FLOYD, EXODUS, TESTAMENT, X-TREME BUGGERY, GUNS N'ROSES, LINSEY, GWAR, ART OF NOISE, JEAN MICHEL JARRE, TANKARD, CINDERELLA, ANTHRAX,  I THINK THAT'S IT NOW, THERE ARE MANY MORE BANDS BUT I RECKON THAT YOU GET PRETTY BORED READING THEM ALL, BASICIALLY WHAT WE LIKE IS HARDCORE AND SPEEDMETAL. TALKING OF GIGS, I WOULD LIKE TO SAY A SPECIAL HI TO THE GUY WE MET AT THE ONSLAUGHT GIG IN THE ASTORIA, THERE IS THIS GUY AND HE JUST COMES UP TO US AND SAYS 'HEY YOU, YOU ARE ONE OF THE LOST BOYS AREN'T YOU ?', I, TOTALLY BAFFELD, REPLY 'YES, BUT HOW DO YOU KNOW' AND HE REPLYS 'I SAW A DIGITIZED PICTURE OF YOU IN A DEMO. BY THE WAY, STAGE DIVING IS GREAT, YOU MUST DO IT, IT IS AN EXCELLENT FEELING WHEN YOU JUMP FROM THE STAGE AND EVERYBODY CATCHES YOU, IF THEY DON'T IT MAY END PRETTY PAINFUL AND A STONE FLOOR IS QUITE HARD.      NOW I WOULD LIKE TO SAY ANOTHER SPECIAL HI TO MY GIRL FRIEND IN GERMANY, BRITTA, WHOM I MET IN ST PETER ORDING, WHICH IS CLOSE TO HUSUM, WHICH IS AGAIN ABOUT 250 KM AWAY FROM HAMBURG IN THE SUMMER OF 1989 (IT WAS  GREAT!!!!!). IF YOU WANT TO KNOW MORE ABOUT MY HOLIDAY THERE, READ EITHER THIS SCROLLER OR THE PD SCROLLER.   ANOTHER SPECIAL HI GOES TO SCOTT WREN WHO ADORES US, HE EVEN ASKED US FOR A SIGNED PICTURE.         NOW WE WOULD WE WOULD LIKE TO TALK ABOUT SOME OTHER DEMOS, THE ONES WE LIKE,   THE CUDDLY DEMOS (WHICH WAS THE BEST DEMO UNTIL WE RELEASED OUR MINDBOMB DEMO WHICH IS DEFINITELY THE BEST DEMO EVER DONE ON AN ATARI ST, WE WOULD LIKE TO CHALLENGE EVERYBODY TO  PRODUCE A BETTER DEMO THAN THIS ONE!!!), ST SQUAD DEMOS (COULD YOU PLEASE IMOPROVE YOU DEMOS A BIT), SPUNK DEMOS (UUPS A SPELLING MISTAKE IT SHOULD BE SKUNK (CAN YOU IMPROVE YOUR SAMPLE QUALITY), BIG DEMO (GREAT MUSIX VERUECKTER MAX,  WAIT UNTIL YOU WILL SEE OUR DEMO WITH MORE PIECES OF MUSIX) FOR MORE THINGS ON DEMOS READ ON..... GET YOUR PD DEMOS FROM THE LOST BOYS PD LIBRARY.    NOW WE WOULD LIKE TO SEND THE ONLY FUCKING GREETING WE HAVE EVER SEND, THEY GO TO  NICK ELLIOT WHO OWNES THE COMPUTER SHOW BARKMANNS IN KINGSTON, NICK YOU ARE ONE OF THE BIGGEST ASSHOLES IN THE HISTORY OF SHOP OWNERS, IF I WERE YOU I WOULD CLOSE YOUR SHOP DOWN. FUUUUUUCK YOU!!!!!!!!!!!! TOMORROW WE WILL CONTINUE  AND FINISH OFF THIS SCROLLER... SEE YA TOMORROW................ .. . ..   .   .   ..  ....      THOSE LAST DOTS WAS BRAILE  SO IF YOUR BLIND HAVE A READ.          BACK AGAIN ,AND THIS TIME IT'S SPAZ ON SAMMY JOES SHIT STAINED KEYBOARD WITH SOME USELESS JOKES ON IT.    SO WHAT DO I HAVE TO TALK ABOUT ???????? NOT ALOT. I KNOW I'LL READ THE LIST AT THE TOP OF THIS SCROLL LIST (PLEASE WAIT)..!.?..!?!!!...........OH FUCK ,WE'VE DONE EVERYTHING IN THE LIST ,I KNOW ,I BET YOUR DYING TO KNOW WHAT HELEN SAID TO ME AT SCHOOL TODAY ,SHE SAID ,WAIT FOR IT , SHE SAID YYYYYYYYEEEEEEEEEESSSSSSSSSS!!!!!!!!!!  WELL WASN'T THAT EXCITING.  SO WE NOW HAVE NOTHING TO TALK ABOUT EXCEPT SAMMY JOES LOVE LIFE, RIGHT HERE WE GO                 WELL THAT WAS INTERESTING WASN'T IT . JUST A MINUTE AGO WE HAD A PHONE CALL FROM SOME GUY WE THOUGHT WAS DEAD BUT APPARENTLY HE DID NOT DIE HE MUTATED INTO AN ANGEL OF DEATH...........    WEWERE ASKED TO WRITE A SCREEN FOR THE OVERLANDERS EUROPEAN DEMO ,SO WE ARE HOPING TO SEND THEM THE OLD THREE-D SPRITES THAT WE HAVE NOW IMPROVED FOR  THE MINDBOMB DEMO. WE HAVE A MESSAGE FOR ALL DEMO CODERS - IF YOU WRITE ANY DEMOS SEND THEM TO US SO WE CAN LOOK AT THEM. I ,SPAZ OF TLB AND MANIKIN (THAT STUPID WANKER) MIGHT BE WRITING A GAME SOON SO WATCH OUT FOR IT ,YOU MIGHT EVEN FIND OUT OUR CORRECT NAMES , ISN'T THAT RIGHT MICHAEL , OH SHIT.     ALRIGHT THEN IT IS SAMMY JOE ON THE KEYBOARD AGAIN, FROM NOW ON I AM JUST GOING TO TALK ABOUT MY SUMMER HOLIDAY 1989,    I HAVE A FRIEND THERE, AND HE'S GOT A MOTORBIKE, SO EACH EVENING WE WENT TO ST PETER ORDING (30 KM FROM WERE WE STAYED) TO GET AN ICE CREAM. ONE EVENING WHEN WE ARRIVED IN ST PETER ORDING, ANOTHER FRIEND IF MINE SUDDENLY REALISED THAT HE WAS RUNNING OUT OF GAS. SO HE WENT OFF TO THE FILLING STATION, A FEW MINUTES LATER  HE CAME BACK AND TOLD US THAT THE FILLING STATION WAS CLOSED.    SO WE DECIDED TO TURN BACK AND SEE HOW FAR WE CAN GET,   WE ABOUT 5 KM AND THEN SUDDENLY IN THE MIDDLE OF NOWHERE HIS ENGINE STOPPED, SO WHAT COULD WE DO ?   WE SAT AT THE SIDE OF THE STREET FOR ABOUT HALF AN  HOUR WHEN FINALLY A CAR CAME, BUT THE BASTARD DIDN'T BOTHER TO STOP, SO AFTER HAVING HAD TO WAIT FOR ABOUT ONE HOUR A CAR FINALLY STOPPED AND WE GOT SOME PETROL!!!!!!     ONE NIGHT WE WENT TO A BIERZELT WHERE WE GOT PISSED OUT OF OUR  BRAINS, BLOODY HELL IT WAS A DANGEROUS RIDE HOME AT 4 O' CLOCK IN THE MORNING.  SO NOW WERE ARE GOING TO SWAP TO GERMAN (OTEHRWISE I WILL TOTALLY FORGET HOW TO SPEAK IT!!),     HALLO LEUTE ICH WREDE JETZT NOCH ETWAS MEHR UEBER MEINE  FERIEN AN DER NORDSEE ERZEAHLEN, VOR ALLEM MOECHTE ICH MEINE FREUNDE DORT GRUESSEN, EINMAL HALKE LOHFF (BIS IN DEN SOMMERFERIEN WENN ICH WIEDER KOMME!!!),  GRILLE (HAST DU DEIN NUES MOTORRAD SCHON GEKAUFT ?), DIE GANZEN SCHOENEN  MAEDCHEN DIE ICH DORT GETROFFEN HABE.        ALLRIGHT LET'S GO BACK TO ENGLISH THEN,     AS WE ARE GETTING VERY BORED WITH THIS (WE STILL MUST WRITE ABOUT 6 OTHER SCROLLERS)  SO  THANKS FOR READING THIS SCROLLER, TELL EVERYBODY ABOUT  THE LOST BOYS PD LIBRARY, LET'S SAY GOOD BYE IN AS MANY LANGUAGES AS WE CAN, LET'S START WITH GERMAN, TSCHUESS/AUF WIEDERSEHEN, VERPISS DICH... IN FRENCH   AU REVOIR, SALUT, EN CULAI (OR SOMETHING LIKE THAT)   IN ENGLISH FUCK OFF,  GOOD BYE, BYE-BYE, BYE-GOOD, PISS OFF, GET FUCKED, SLEEP WELL,  AND NOW THE GERMAN ONE AGAIN  TTTTTTTTTTTTTSSSSSSSSSSSSCCCCCCCCCCCHHHHHHHHHHUUUUUUUUUEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS         ";
	this.scrolltext.init(this.scrollcanvas,this.font,12);

 	this.scrollcanvas.contex.imageSmoothingEnabled = false;
  	this.scrollcanvas.contex.mozImageSmoothingEnabled = false;
	this.scrollcanvas.contex.oImageSmoothingEnabled = false;
	this.scrollcanvas.contex.webkitImageSmoothingEnabled = false;
  }

  // Starts the demo and returns a Promise that will be resolved at the end
  // of the demo.
  start() {
    return new Promise(endCallback => {
      this.endCallback = endCallback;
      this.mycanvas=new canvas(768,540,"main");
      this.mycanvas.contex.imageSmoothingEnabled = false;
      this.mycanvas.contex.mozImageSmoothingEnabled = false;
      this.mycanvas.contex.oImageSmoothingEnabled = false;
      this.mycanvas.contex.webkitImageSmoothingEnabled = false;
      document.body.addEventListener('keydown', this.onKeyPressed);
      this.zik.play();
      window.requestAnimFrame(this.main);
    });
  }

  // Main loop, called by Codef requestAnimFrame
  main() {
    if (this.running) {
      this.mycanvas.fill('#000000');
      this.scrollcanvas.clear();

      this.bckdrop.draw(this.mycanvas,0,0,1,0,200,1);

      this.bob+=this.bobinc;
      if (this.bobinc<0.006){
        this.bobinc+=0.000025;
      }

      this.bgcanvas.draw(this.backgroundcanvas,768/4+(768/2*Math.cos(this.bob*4-Math.cos(this.bob-0.1))),540/2.7+(540/2.4*-Math.sin(this.bob*4-Math.cos(this.bob-0.1))));	

      this.bob1+=0.004;
      this.tlb_sprite.draw(this.backgroundcanvas,208/2+(768/8.5*Math.cos(this.bob1*4-Math.cos(this.bob1-0.1))),-70+540/2.7+(540/5*-Math.sin(this.bob1*4-Math.cos(this.bob1-0.1))));	
      this.tlb_sprite.draw(this.backgroundcanvas,708/2+(768/8.5*Math.cos(this.bob1*4-Math.cos(this.bob1-0.1))),-70+540/2.7+(540/5*-Math.sin(this.bob1*4-Math.cos(this.bob1-0.1))));	

      this.backgroundcanvas.draw(this.mycanvas,64,60);

      this.scrolltext.draw(2);
      this.scrollcanvas.draw(this.mycanvas,64,450);
      window.requestAnimFrame(this.main);
    } else {
      this.end();
    }
  }

  stop() {
    this.running = false;
  }

  // removes event listeners before notifying the menu screen that the demo is finished
  end() {
    document.body.removeEventListener('keydown', this.onKeyPressed);
    this.zik.stop();
    this.endCallback();
  }

  // Event processor
  onKeyPressed(event) {
    if (event.key === ' ') {
      event.preventDefault();
      this.stop();
    }
  }
}