class ScrollMassacre {
  constructor(demoManager) {
    this.demoManager = demoManager;
    // Bind to this all internally called functions
    this.onKeyPressed = this.onKeyPressed.bind(this);
    this.main = this.main.bind(this);
    this.stop = this.stop.bind(this);
    this.end = this.end.bind(this);
  }

  // Loads resources and returns a Promise
  // You can make long precalculations here.
  load() {
    return Promise.all(this.demoManager.loadResource(['army_16x16.png', 'bold_64x32.png', 'thin_32x32.png', 'megadeath-blue_128x128.png'])).then(data => {
      [this.tinyFont, this.roundFont, this.thinFont, this.bigFont] = data;
    });
  }

  // Initialize the demo (all resources are already loaded)
  // Initialize scrolltexts here (for example)
  init() {
    this.tinyFont.initTile(16,16,32);
    this.roundFont.initTile(64,32,32);
    this.thinFont.initTile(32,32,32);
    this.bigFont.initTile(128,128,32);
    text1 = "YEAH! LOADSA SCROLLINES. CODED BY MANIKIN OF THE LOST BOYS FOR THE MINDBOMB DEMO, BECAUSE I WAS BORED AND HAD AN HOUR TO SPARE ONE SUNDAY AFTERNOON IN MANCHESTER!!!  TLB HAVE THE FASTEST CODE ON THE ST.. WE ARE THE BEST, FORGET THE REST!!";
    text2 = "AHHH! YET MORE SCROLLS. I THINK IF YOU COUNT YOU WILL FIND THAT THERE ARE ABOUT FORTY LINES ON THIS SCREEN. NOT BAD HUH?  AND WHATS MORE SOME OF THEM ARE ALMOST READABLE!  WELL I DID SAY SOME THAT CERTAINLY DOES NOT MEAN ALL!!!";
    text3 = "FOR ANYONE INTERESTED THIS SCREEN WAS COMPLETED AT THREE IN THE MORNING ON THE TENTH OF FEBRUARY NINETEEN NINETY WHILE UNDER THE INFLUENCE OF A HEAVY NIGHTS DRINKING. I HAVE ABSOLUTELY NO IDEA HOW I MANAGED TO GET THE CODE TOWORK!!!!";
    text4 = "AND FINALLY HERE IS THE FINALE FOR THIS SCREEN[  I THINK THAT THIS IS QUITE ENOUGH SCROLLS DO YOU NOT]    THIS IS THE DID YOU KNOW THAT] SCROLLINE[   IT CONTAINS STUPID FACTS AND FIGURES AND USELESS IN FORMATION ABOUT THIS MAMMOTH DEMO AND ITS PRODUCTION TEAM[ FIRST OF ALL THE LOST BOYS HAVE THREE MEMBERS[   MANIKIN[  WHO DOES ALL THE CODING AND SHIT[   SPAZ WHO DOES MOST OF THE GRAPHICS[ AND SAMMY JOE WHO DOES MOST OF THE SELLING AND LETTER WRITING AND BASICALLY KEEPS THE LOST BOYS RUNNING\  THIS DISK IS THE BIGGEST DEMO OF ITS KIND EVER CODED ON THE ST[  THIS DISK CONTAINS OVER TWO MEGABYTES CODE AND SCREENS PACKED ONTO A STANDARD TEN SECTOR FORMATTED DISK[  ITS TAKEN US OVER ONE YEAR TO COMPLETE THIS ENORMOUS DEMO ALTHOUGH NONE OF THE ORIGINAL SCREENS WRITTEN ARE NOW INCLUDED ON THIS DISK[ THE OLDEST SCREEN IS THE LANDSCAPE SCREEN AND THIS WAS FINISHED IN EARLY JUNE LAST YEAR[ THE NEWEST SCREEN ON THIS DISK IS THE DIGISYNTH SCREEN AND THIS WAS CODED AT THE VERY END OF MARCH NINETEEN NINETY[ THE PROGRAMMING TOOLS USED ON TO CREATE THIS DEMO WERE DEVPAC ST FOR ALL ASSEMBLER CODING[ DEGAS ELITE FOR ALL GRAPHICS AND GFA BASIC FOR THE MANY AND VARIED WAVES AND DATA[  ALL MEMBERS OF THE LOST BOYS ARE UNDER TWENTY YEARS OF AGE AND WE THINK THIS PROBALY MAKES US ONE OF THE YOUNGEST ACTIVE CREWS ON THE ST[ MANIKIN IS NINETEEN AND CURRENTLY STUDYING SOFTWARE ENGINEERING AT MANCHESTER UNIVERSITY[  SAMMY JOE IS SIXTEEN AND CURRENTLY DOING HIS OBERSTUFE AT THE GERMAN SCHOOL IN LONDON[ SPAZ IS ALSO SIXTEEN AND CURRENTLY STUDYING FOR HIS GCSE EXAMS AT A SECONDARY SCHOOL IN TEDDINGTON[  SAMMY JOE AND SPAZ LOVE HEAVY AND SPEED METAL MUSIC[ MANIKIN HATES HEAVY METAL AND LIKES ALMOST EVERYTHING ELSE[ WE ALL HATE ANYTHING PRODUCED BY STOCK AITKEN OR WATERMAN AND WOULD GLADLY PUKE ON JASON DONAVANS HEAD[  WE HAVE ALSO HEARD THAT KYLIE MINOUGUE GIVES GOOD HEAD AND WOULD THEREFORE LIKE TO MEET HER\ SNAKE HAS A BIG NOSE[ CHUCK OF FOXX TOLD ME THIS AND SAID THAT I SHOULD TYPE IT SOMEWHERE\[ ONE OF OUR BEST CONTACTS FOR HACKED SOFTWARE IS A PRIEST[ NO KIDDING\ REALLY\  IS THE COPYING OF SOFTWARE ILLEGAL IN THE EYES OF GOD WE ASK] COKE IS ONE OF THE NICEST DRINK IN THE WORLDS BUT NEWCASTLE BROWN ALE IS BETTER[ SPAZ HAS LONG HAIR AND LOOKS LIKE A WOMBLE[ SAMMY JOE IS GERMAN BUT ITS NOT HIS FAULT\ MANIKIN HAS GREY HAIR AND HENCE IS KNOWN AS AN OLD MAN\  WE ONCE HAD A LETTER FROM A LITTLE KID WHO WANTED A SIGNED PHOTOGRAPH OF US[ WE WERE IMPRESSED BY HIS GOOD TASTE BUT I DO NOT THINK THAT HE GOT THE PHOTO\  THE STRANGEST PLACE THAT WE HAVE YET RECIEVED A LETTER FROM IS      WAIT FOR IT\          MOSCOW IN RUSSIA FROM A DENNIS ZUBCHOW\  YO GUY\     WE HAVE ALSO HAD LETTERS FROM EVERY COUNTRY IN EUROPE WITHOUT EXCEPTION AND THE FURTHEST LETTER WE HAVE HAD IS FROM SEWERSOFT IN AUSTRALIA AND I DOUBT IF WE WILL EVER BEAT THAT\ RICHARD KARSMAKERS LOOKS EXTREMELY SILLY IN A SUIT\    STEFAN POSTHUMA IS TWENTY THREE YEARS OLD ON APRIL FOURTEENTH AND I AM GOING TO HIS BIRTHDAY PARTY IN UTRECHT[  THIS DEMO WAS FINALLY COMPLETED AT THALION SOFTWARE IN THE COMPANY OF TCB AND TEX[    I AM RUNNING OUT OF THINGS TO SAY VERY RAPIDLY\         WE ARE GOING TO SELL THE SOURCE LISTINGS FOR SCREENS IN THIS DEMO AGAIN[   MANY PEOPLE WILL PROBABLY THINK WE ARE EXTREMELY MAD TO DO THIS BUT WE ARE IN BAD NEED OF SOME MONEY AND IT WORKED REALLY WELL LAST TIME SO WE DECIDED TO DO IT AGAIN\  EACH INDIVIDUAL SCREEN WILL BE AVAILABLE FROM THE LOST BOYS AT THE  BARGAIN PRICE OF TEN POUNDS STERLING EACH[ UNFORTUNATELY WE WILL NOT BE SELLING THE SOURCE FOR THE MAIN MENU OR THE SOURCE FOR OUR DIGISYNTH AS THEY ARE TOO VALUABLE TO US[ IF YOU WANT TO BUY A SCREEN THEN WRITE TO US AT THE ADDRESS  ELSEWHERE IN THIS DEMO[ CHEQUES SHOULD BE MADE PAYABLE TO DAVID MOSS[ SPAZ[   IF ANYONE ELSE IS INTERESTED MANIKINS NAME IS TIM MOSS[ WE ARE BROTHERS SURPRISINGLY ENOUGH AND SAMMY JOES NAME IS MICHAEL SHUESSLER[ WE ARE VERY PROUD OF THIS DEMO AND HAVE PUT AN EXTREMELY LARGE AMOUNT OF HARD WORK INTO IT[ IF YOU FEEL LIKE DONATING MONEY TO US THEN THIS WOULD BE VERY WELL RECIEVED AND YOU WOULD FOREVER HAVE OUR GRATITUDE[  AS YOU WILL ALREADY KNOW THIS DEMO IS NOT PUBLIC DOMAIN AND IS LICENSED TO BUDGIE UK[ YOU MUST THEREFORE HAVE AN AGREEMENT WITH BUDGIE UK OR LOST BOYS BEFORE YOU SELL OUR DEMOS OR WE PROMISE THAT YOU WILL HAVE THE FULL WAIT OF  F[A[S[T[ DOWN ON YOUR HEAD FOR DEFRAUDING US\\  THIS THEN CONCLUDES OUR SCROLLTEXT FOR THIS SCREEN[ LETS WRAP\\\\\\\\             ";
    
    this.running = true;    
  }

  // Starts the demo and returns a Promise that will be resolved at the end
  // of the demo.
  start() {
    return new Promise(endCallback => {
      this.endCallback = endCallback;
      this.can = new canvas(640, 400, "main");
      this.ctx = this.can.contex;
      document.body.addEventListener('keydown', this.onKeyPressed);
      setTimeout(this.stop, 4500);
      window.requestAnimFrame(this.main);
    });
  }

  // Main loop, called by Codef requestAnimFrame
  main() {
    if (this.running) {
      this.introImage.draw(this.can, 16, 16);
      this.ctx.font = 'bold 24px "Comic sans MS", serif';
      this.ctx.fillStyle = '#F80';
      this.ctx.textAlign = 'center';
      this.ctx.fillText("This will be the " + this.constructor.name + " demo.", 320, 200);
      window.requestAnimFrame(this.main);
    } else {
      this.end();
    }
  }

  stop() {
    this.running = false;
  }

  // removes event listeners before notifying the menu screen that the demo is finished
  end() {
    document.body.removeEventListener('keydown', this.onKeyPressed);
    this.endCallback();
  }

  // Event processor
  onKeyPressed(event) {
    if (event.key === ' ') {
      event.preventDefault();
      this.stop();
    }
  }
}